# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CV\ProjManager\ManagerP.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectManager(object):
    def setupUi(self, ProjectManager):
        ProjectManager.setObjectName("ProjectManager")
        ProjectManager.resize(1517, 203)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProjectManager.sizePolicy().hasHeightForWidth())
        ProjectManager.setSizePolicy(sizePolicy)
        ProjectManager.setWindowTitle("Project Manager")
        ProjectManager.setToolTip("")
        ProjectManager.setStatusTip("")
        ProjectManager.setWhatsThis("")
        ProjectManager.setAccessibleName("")
        ProjectManager.setAccessibleDescription("")
        ProjectManager.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(220, 255, 253);")
        self.centralwidget = QtWidgets.QWidget(ProjectManager)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 7, 1521, 250))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setWhatsThis("")
        self.label.setAccessibleName("")
        self.label.setAccessibleDescription("")
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel {\n"
"                background-image:url(:/icon/Brxx.png);\n"
"                background-repeat: no-repeat;\n"
"                background-position: right center;\n"
"                padding-right: 10px;\n"
"                min-height: 50px;\n"
"                min-width: 100px;\n"
"            }")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(64)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(620, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setToolTip("")
        self.tableWidget.setStatusTip("")
        self.tableWidget.setWhatsThis("")
        self.tableWidget.setAccessibleName("")
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setLineWidth(6)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setText("Name")
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(47, 79, 79))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Status")
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(47, 79, 79))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Run Time")
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(47, 79, 79))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 79, 79))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Stop Time")
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Timer")
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Settings")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 2, item)

        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.tableWidget)

        #**************************************************************

        self.Open = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Open.sizePolicy().hasHeightForWidth())
        self.Open.setSizePolicy(sizePolicy)
        self.Open.setMinimumSize(QtCore.QSize(0, 50))
        self.Open.setMaximumSize(QtCore.QSize(200, 80))
        self.Open.setSizeIncrement(QtCore.QSize(0, 0))
        self.Open.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Open.setFont(font)
        self.Open.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Open.setMouseTracking(True)
        self.Open.setToolTip("")
        self.Open.setStatusTip("")
        self.Open.setWhatsThis("")
        self.Open.setAccessibleName("")
        self.Open.setAccessibleDescription("")
        self.Open.setAutoFillBackground(False)
        self.Open.setStyleSheet("QPushButton {\n"
                                "    color: white;\n"
                                "    border: 2px solid #43C6AC;\n"
                                "    border-bottom-left-radius: 25px;\n"
                                "    border-shadow: -5px -5px -5px rgba(0, 0, 0, 1);\n"
                                "    border-style: outset;\n"
                                "    background: #3914AF;\n"
                                "    padding:5px;\n"
                                "    text-align: left;\n"
                                "    }\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    background: qradialgradient(\n"
                                "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                "        radius: 1.35, stop:  0 #fff, stop: 1 #B2FEFA\n"
                                "        );\n"
                                "    }\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    border-style: inset;\n"
                                "    background: qradialgradient(\n"
                                "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                "        radius: 1.35, stop: 0 #0ED2F7, stop: 1 #0ED2F7\n"
                                "        );\n"
                                "    }")
        self.Open.setText("LogFile ")
        # icon1 = QtGui.QIcon()
        # icon1.addPixmap(QtGui.QPixmap("E:\\Py\\LTE\\icon\\icons8-звуковой-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.Open.setIcon(icon1)
        # self.Open.setIconSize(QtCore.QSize(32, 32))
        self.Open.setObjectName("Open")
        #*************************************************************************

        ProjectManager.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProjectManager)
        QtCore.QMetaObject.connectSlotsByName(ProjectManager)

    def retranslateUi(self, ProjectManager):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("ProjectManager", "<html><head/><body><p align=\"center\">Project Manager</p></body></html>"))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)

        self.tableWidget.setSortingEnabled(__sortingEnabled)
import PM_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectManager = QtWidgets.QMainWindow()
    ui = Ui_ProjectManager()
    ui.setupUi(ProjectManager)
    ProjectManager.show()
    sys.exit(app.exec_())
